spring:
  profiles:
    active: local
  application:
    name: StaySync

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/stay_sync_db?useUnicode=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: password
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5

  jpa:
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        #Hibernate Full Text search
        dialect: org.hibernate.dialect.MySQL8Dialect
        type: trace
        dialect.storage_engine: innodb
      hibernate.search:
        backend:
          type: lucene
          lucene_version: LATEST
          analysis.configurer: luceneAnalysisConfiguration
          directory.root: opt/indexes

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus, scheduledtasks

server:
#  port: 8090
  forward-headers-strategy: framework
  error:
    include-message: always
  http2:
    enabled: true
  tomcat:
    threads:
      max: 5
      min-spare: 1
env:
  local: http://localhost:8090/
  dev: http://localhost:8080/
  prod: http://localhost:8090/

security:
  jwt:
    tokenIssuer: https://yatrionyatra.com
    tokenSigningKey: dev-secret-key-to-be-used-should-be-512-bit-at-least-otherwise-it-will-just-fail
    tokenExpirationTime: 30 # Minutes

aws:
  accessKeyId: YOUR_ACCESS_KEY
  secretKey: YOUR_SECRET_KEY
  region: YOUR_REGION
  s3:
    bucketName: YOUR_BUCKET_NAME

#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest



